package it.unina.is.russo.ken.daoexaple;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class EntityDAO {
	
	static Entity create(String initialState){
		Connection c = DBManager.getConnection();
		Entity e = new Entity(initialState);
		System.out.println("Creation of an entry with state: "+initialState);

		try(Statement stmt = c.createStatement()){
			
			stmt.executeUpdate("INSERT INTO ENTITIES (STATO) VALUES ('"+initialState+"')");
			ResultSet rs = stmt.getGeneratedKeys();
			if (rs.next() == false){
				throw new SQLException("ID value was not autogenerated!");
			}
			System.out.println("Creation done. Auto-genreated ID "+rs.getInt(1));
			e.setId(rs.getInt(1));
			
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		if (e.getId() == null)
			e = null;
		return e;
	}
	
	static Entity read(Integer id){
		if (id == null) return null;
		System.out.println("Reading entry with ID: "+id);
		Connection c = DBManager.getConnection();
		Entity e = null;
		try(Statement stmt = c.createStatement()){
			
			ResultSet rs = stmt.executeQuery("SELECT * FROM ENTITIES WHERE ID=" +id.toString()+";");
			if (rs.next() == false){
				throw new SQLException("ID value not found!");
			}
			e = new Entity(rs.getString("STATO"));
			e.setId(id);
			System.out.println("Read Entity with ID "+e.getId()+", state "+e.getState());
			
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		return e;
	}
	
	static void update(Entity e){
		if (e==null) return;
		System.out.println("Updating entry with ID: "+e.getId());
		if (e.getId() == null){
			Entity newEntity = create(e.getState());
			e.setId(newEntity.getId());
		}else{
			Connection c = DBManager.getConnection();
			try(Statement stmt = c.createStatement()){
				
				stmt.executeUpdate("UPDATE ENTITIES SET STATO='"+e.getState()+"' WHERE ID=" +e.getId()+";");
				
			System.out.println("Update done.");
			} catch (SQLException ex) {
				ex.printStackTrace();
			}

		}
		
	}
	
	static void delete(Entity e){
		
		if (e == null || e.getId() == null) return;
		System.out.println("Deleting entry with ID: "+e.getId());
		Connection c = DBManager.getConnection();
		try(Statement stmt = c.createStatement()){
			
			stmt.executeUpdate("DELETE FROM ENTITIES WHERE ID=" +e.getId()+";");
			e.setId(null);
			
			System.out.println("Deletion done.");
			
		} catch (SQLException ex) {
			ex.printStackTrace();
		}

	}

}
