package is.example;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Articolo.java
//  @ Date : 23/05/2013
//  @ Author : 
//
//




public class Articolo {
	private String nome;
	private int qnt;
	private int prezzo;
	
	
	
	public Articolo(String nome, int qnt, int prezzo) {
		super();
		this.nome = nome;
		this.qnt = qnt;
		this.prezzo = prezzo;
	}

	public String getNome() {
		return nome;
	}
	
	public int getQnt() {
		return qnt;
	}
	
	public int getPrezzo() {
		return prezzo;
	}
	
	public boolean changeQnt(int diff) {
		if (diff >= 0 || qnt+diff >= 0) {
			qnt += diff;
			return true;
		}
		return false; 
	}
}
