package is.example;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CartaDebito.java
//  @ Date : 23/05/2013
//  @ Author : 
//
//




public class CartaDebito extends Carta {
	
	public void deposita(int m) {
		saldo += m;
	}
	
	
	public boolean preleva(int p) {
		if (saldo-p >= 0) {
			saldo = saldo -p;
			return true;
		}
		return false;
	}
}
