package is.example;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Carta.java
//  @ Date : 23/05/2013
//  @ Author : 
//
//




public abstract class Carta implements StrumentoPagamento {
	protected int saldo;
	protected Persona intestatario;
	
	public int getSaldo() {
		return saldo;
	}
	
	public abstract boolean preleva(int prezzo);
	
	
	public Persona getIntestatario() {
		return intestatario;
	}
}
