package is.example;



//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CartaCredito.java
//  @ Date : 23/05/2013
//  @ Author : 
//
//




public class CartaCredito extends Carta {
	
	private int massimale;
		
	public void setMassimale(int m) {
		massimale = m;
	}
	
	
	
	@Override
	public boolean preleva(int p) {
		if (saldo-p >= -massimale) {
			saldo = saldo - p;
			return true;
		}
		return false;
	}



	public int getMassimale() {
		return massimale;
	}
	
	public void ripristinaSaldo() {
		saldo = massimale;
	}
	
	
}
