package is.example;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.java
//  @ Date : 23/05/2013
//  @ Author : 
//
//




public class Persona {
	private String nome;
	private String indirizzo;
	private ArrayList<ContoCorrente> contiCorrente;
	private ArrayList<Carta> carte;
	
	public Persona(String nome, String indirizzo) {
		this.nome = nome; 
		this.indirizzo = indirizzo; 
		contiCorrente = new ArrayList<ContoCorrente>(); 
		carte = new ArrayList<Carta>();
		
	}
	
	public void addContoCorrente(ContoCorrente c) {
		contiCorrente.add(c);
	}
	
	public void addCarta(Carta c) {
		carte.add(c);
	}
	
	public ContoCorrente[] getContiCorrente() {
		ContoCorrente cc[] = new ContoCorrente[contiCorrente.size()];
		for (int i = 0; i < contiCorrente.size(); i++)
			cc[i] = contiCorrente.get(i);
		return cc;
		//Oppure
		//ContoCorrente cc[] = (ContoCorrente[])contiCorrente.toArray();
	}
	
	public Carta[] getCarte() {
		Carta c[] = new Carta[carte.size()];		
		for (int i = 0; i < carte.size(); i++)
			c[i] = carte.get(i);
		return c;
		//Oppure:
		//Carta c[] = (Carta[])carte.toArray();
 	}
}
