package is.example;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StrumentoPagamento.java
//  @ Date : 23/05/2013
//  @ Author : 
//
//




public interface StrumentoPagamento {
	public int getSaldo();
	public boolean preleva(int prezzo);
	public Persona getIntestatario();
}
