package is.example;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ContoCorrente.java
//  @ Date : 23/05/2013
//  @ Author : 
//
//




public class ContoCorrente implements StrumentoPagamento {
	private String iban;
	private int saldo;
	private int maxScoperto;
	private Persona intestatario;
	
	public void deposita(int v) {
		saldo += v;
	}
	
	public String getIban() {
		return iban;
	}
	
	public int getSaldo() {
		return saldo;
	}
	
	public boolean preleva(int p) {
		if (saldo-p >= -maxScoperto) {
			saldo = saldo -p;
			return true;
		}
		return false;
	}
	
	public Persona getIntestatario() {
		return intestatario;
	}
}
